version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
      - TZ=America/Bogota
      - ES_JAVA_OPTS=-Xmx6g
    networks:
      - elk

  kibana:
    image: kibana:8.11.0
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d
      - TZ=America/Bogota
    networks:
      - elk

  logstash:
    image: logstash:8.11.0
    container_name: logstash
    restart: always
    ports:
      - 5000:5000
      - 9201:9201
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - MONITORING_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - MONITORING_ENABLED=false
      - TZ=America/Bogota
      - LS_JAVA_OPTS=-Xmx1g
    networks:
      - elk

networks:
  elk:
    driver: bridge
