apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: gmacastil/curso-micros-cloudnative
    sonarqube.org/project-key: curso-micros-cloudnative
  description: Repositorio para un curso sobre microservicios y aplicaciones nativas
    en la nube utilizando tecnologías como Docker, Kubernetes, y patrones de diseño.
  name: curso-micros-cloudnative
  tags:
  - docker
  - kubernetes
  - java
  - patronesdediseño
spec:
  lifecycle: production
  owner: gmacastil
  system: dummy
  type: service
