apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: gmacastil/curso-micros-cloudnative
    sonarqube.org/project-key: curso-micros-cloudnative
  description: "Repositorio para un curso sobre microservicios y aplicaciones nativas\
    \ en la nube utilizando tecnolog\xEDas como Docker, Kubernetes, y patrones de\
    \ dise\xF1o."
  name: curso-micros-cloudnative
  tags:
  - docker
  - kubernetes
  - java
  - "patronesdedise\xF1o"
spec:
  lifecycle: production
  owner: gmacastil
  system: dummy
  type: service
